## Imports
from pydantic import BaseModel, Field
from typing import Optional, List, Dict, Any

class ProjectData(BaseModel):
    """
    Schema for a real estate project in the system.

    Represents a property project and its main attributes, including identification, location, pricing, 
    features, and descriptive metadata. All fields except 'id' are nullable in the database.

    Database Table: projects
    
    Attributes:
        id (Optional[int])                           : Unique identifier for the project. Auto-generated by database.
        project_name (Optional[str])                 : Name/title of the real estate project.
        no_of_bedrooms (Optional[int])               : Number of bedrooms in the property.
        completion_status (Optional[str])            : Project completion status (e.g., "off plan", "available").
        bathrooms (Optional[int])                    : Number of bathrooms in the property.
        unit_type (Optional[str])                    : Type of property unit (e.g., "apartment", "villa").
        developer_name (Optional[str])               : Name of the real estate developer.
        price_usd (Optional[float])                  : Listing price in US Dollars.
        area_sq_mtrs (Optional[float])               : Total area of the property in square meters.
        property_type (Optional[str])                : Property category (e.g., "apartment", "villa").
        city (Optional[str])                         : City where the project is located.
        country (Optional[str])                      : Country where the project is located.
        completion_date (Optional[str])              : Projected or actual completion date (format: YYYY-MM-DD).
        features (Optional[List[str]])               : List of offered property features (stored as JSON in TEXT field).
        facilities (Optional[List[str]])             : List of available facilities within the project (stored as JSON in TEXT field).
        project_description (Optional[str])          : Detailed information and description of the project.
        created_at (Optional[str])                   : Timestamp (ISO format) when the record was first created.
        updated_at (Optional[str])                   : Timestamp (ISO format) of the last update to the record.
    """
    
    # Database table name
    __table_name__ = "projects"

    id: Optional[int] = Field(
        default=None, 
        description="Unique identifier for the project. Auto-generated by database."
    )
    project_name: Optional[str] = Field(
        default=None, 
        description="Name of the property project."
    )
    no_of_bedrooms: Optional[int] = Field(
        default=None, 
        description="Number of bedrooms in the property."
    )
    completion_status: Optional[str] = Field(
        default=None, 
        description="Completion status of the project (e.g., 'off plan', 'available')."
    )
    bathrooms: Optional[int] = Field(
        default=None, 
        description="Number of bathrooms in the property."
    )
    unit_type: Optional[str] = Field(
        default=None, 
        description="Type of unit (e.g., apartment, villa)."
    )
    developer_name: Optional[str] = Field(
        default=None, 
        description="Name of the developer or development company."
    )
    price_usd: Optional[float] = Field(
        default=None, 
        description="Property price in US Dollars."
    )
    area_sq_mtrs: Optional[float] = Field(
        default=None, 
        description="Total area of the property in square meters."
    )
    property_type: Optional[str] = Field(
        default=None, 
        description="Category/type of property (apartment/villa)."
    )
    city: Optional[str] = Field(
        default=None, 
        description="City where the property is located."
    )
    country: Optional[str] = Field(
        default=None, 
        description="Country where the property is located."
    )
    completion_date: Optional[str] = Field(
        default=None, 
        description="Expected or actual property completion date (YYYY-MM-DD)."
    )
    features: Optional[List[str]] = Field(
        default=None, 
        description="List of features available in the property."
    )
    facilities: Optional[List[str]] = Field(
        default=None, 
        description="List of facilities provided in the project."
    )
    project_description: Optional[str] = Field(
        default=None, 
        description="Detailed narrative/description of the project."
    )
    created_at: Optional[str] = Field(
        default=None, 
        description="Timestamp when the record was created (ISO format)."
    )
    updated_at: Optional[str] = Field(
        default=None, 
        description="Timestamp when the record was last updated (ISO format)."
    )



class LeadData(BaseModel):
    """
    Schema for a potential customer lead.

    Represents leads interested in buying or renting properties, capturing key contact information and
    property preferences. All fields except 'id' are nullable in the database.

    Database Table: leads
    
    Attributes:
        id (Optional[int])                            : Unique identifier for the lead. Auto-generated by database.
        first_name (Optional[str])                    : First name of the customer.
        last_name (Optional[str])                     : Last name of the customer.
        email (Optional[str])                         : Contact email address.
        preferred_city (Optional[str])                : City where the customer prefers to find a property.
        preferred_budget_usd (Optional[int])         : Customer's budget in USD.
        preferred_property_type (Optional[str])       : Preferred type of property (e.g., "apartment", "villa").
        preferred_bedrooms (Optional[int])            : Preferred number of bedrooms.
        metadata_json (Optional[Dict[str, Any]])     : Additional data or preferences (stored as JSON in TEXT field).
        created_at (Optional[str])                    : Timestamp (ISO format) when the lead record was created.
        updated_at (Optional[str])                    : Timestamp (ISO format) when the lead record was last updated.
    """
    
    # Database table name
    __table_name__ = "leads"

    id: Optional[int] = Field(
        default=None, 
        description="Unique identifier for the lead. Auto-generated by database."
    )
    first_name: Optional[str] = Field(
        default=None, 
        description="First name of the customer lead."
    )
    last_name: Optional[str] = Field(
        default=None, 
        description="Last name of the customer lead."
    )
    email: Optional[str] = Field(
        default=None, 
        description="Email address of the customer lead."
    )
    preferred_city: Optional[str] = Field(
        default=None, 
        description="Preferred city for property search."
    )
    preferred_budget_usd: Optional[int] = Field(
        default=None, 
        description="Maximum property budget (in USD)."
    )
    preferred_property_type: Optional[str] = Field(
        default=None, 
        description="Preferred type of property (e.g., 'apartment', 'villa')."
    )
    preferred_bedrooms: Optional[int] = Field(
        default=None, 
        description="Preferred number of bedrooms in the property."
    )
    metadata_json: Optional[Dict[str, Any]] = Field(
        default=None,
        description="Additional preferences or metadata for the lead (stored as JSON in TEXT field)."
    )
    created_at: Optional[str] = Field(
        default=None, 
        description="Timestamp when the lead record was created (ISO format)."
    )
    updated_at: Optional[str] = Field(
        default=None, 
        description="Timestamp when the lead record was last updated (ISO format)."
    )

class BookingData(BaseModel):
    """
    Schema for a property booking record.

    Represents the relationship between a customer lead and a project, capturing the booking event and its status.
    All fields except 'id' are nullable in the database.

    Database Table: bookings

    Attributes:
        id (Optional[int])                  : Unique identifier for the booking record. Auto-generated by database.
        lead_id (Optional[int])             : Foreign key reference to the customer lead who made the booking.
        project_id (Optional[int])          : Foreign key reference to the booked property/project.
        booking_date (Optional[str])        : Date when the booking was made (format: YYYY-MM-DD).
        booking_status (Optional[str])      : Current status of the booking (e.g., "confirmed", "pending", "cancelled").
        created_at (Optional[str])          : Timestamp (ISO format) when the booking record was created.
        updated_at (Optional[str])          : Timestamp (ISO format) when the booking record was last updated.
    """
    
    # Database table name
    __table_name__ = "bookings"

    id: Optional[int] = Field(
        default=None, 
        description="Unique identifier for the booking record. Auto-generated by database."
    )
    lead_id: Optional[int] = Field(
        default=None, 
        description="Foreign key reference to the lead who made the booking."
    )
    project_id: Optional[int] = Field(
        default=None, 
        description="Foreign key reference to the booked project/property."
    )
    booking_date: Optional[str] = Field(
        default=None, 
        description="Date the booking was made (format: YYYY-MM-DD)."
    )
    booking_status: Optional[str] = Field(
        default=None,
        description="Current booking status (e.g., 'confirmed', 'pending', 'cancelled')."
    )
    created_at: Optional[str] = Field(
        default=None, 
        description="Timestamp when the booking record was created (ISO format)."
    )
    updated_at: Optional[str] = Field(
        default=None, 
        description="Timestamp when the booking record was last updated (ISO format)."
    )

class HistoryData(BaseModel):
    """
    Schema for chat or conversation history entry.

    Represents a single message or interaction within a conversation session, optionally linked to a customer lead.
    The 'conversation_id' and 'role' fields are required (NOT NULL in database).

    Database Table: history

    Attributes:
        id (Optional[int])                  : Unique identifier for the history entry. Auto-generated by database.
        conversation_id (str)               : Identifier for the conversation session (e.g., a UUID). Required field.
        lead_id (Optional[int])             : Foreign key to the related lead if this conversation is associated with a customer.
        created_at (Optional[str])          : Timestamp (ISO format) when the message was created.
        updated_at (Optional[str])          : Timestamp (ISO format) when the message was last updated.
    """
    
    # Database table name
    __table_name__ = "history"

    id: Optional[int] = Field(
        default=None, 
        description="Unique identifier for the history record. Auto-generated by database."
    )
    conversation_id: str = Field(
        ..., 
        description="Identifier for the conversation session (e.g., UUID string). Required field."
    )
    lead_id: Optional[int] = Field(
        default=None, 
        description="Reference to the associated lead (if any). Foreign key to leads.id."
    )
    created_at: Optional[str] = Field(
        default=None, 
        description="Timestamp when the history record was created (ISO format)."
    )
    updated_at: Optional[str] = Field(
        default=None, 
        description="Timestamp when the history record was last updated (ISO format)."
    )

